/**
 * STUB — replaced by `npx convex dev` / `npx convex codegen`.
 *
 * This file exists so the rest of the codebase typechecks before Convex's
 * code generator has run. The shape mirrors what convex generates so that
 * the regenerated version is a drop-in replacement.
 *
 * DO NOT edit this file directly — edit `convex/schema.ts` and run
 * `npx convex dev` to regenerate.
 */
import {
  type GenericActionCtx,
  type GenericMutationCtx,
  type GenericQueryCtx,
  type DataModelFromSchemaDefinition,
  actionGeneric,
  mutationGeneric,
  queryGeneric,
  internalActionGeneric,
  internalMutationGeneric,
  internalQueryGeneric,
  httpActionGeneric,
} from "convex/server";
import schema from "../schema";

export type DataModel = DataModelFromSchemaDefinition<typeof schema>;
export type QueryCtx = GenericQueryCtx<DataModel>;
export type MutationCtx = GenericMutationCtx<DataModel>;
export type ActionCtx = GenericActionCtx<DataModel>;

export const query = queryGeneric;
export const mutation = mutationGeneric;
export const action = actionGeneric;
export const internalQuery = internalQueryGeneric;
export const internalMutation = internalMutationGeneric;
export const internalAction = internalActionGeneric;
export const httpAction = httpActionGeneric;
